server {
    listen 80;
    listen [::]:80;
    server_name geo.miaomiaoxiaoxianer.cn;

    root /www/wwwroot/geo.miaomiaoxiaoxianer.cn;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|webp|ico|woff|woff2|mp4|pdf)$ {
        try_files $uri =404;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    access_log /www/wwwlogs/geo.miaomiaoxiaoxianer.cn.log;
    error_log /www/wwwlogs/geo.miaomiaoxiaoxianer.cn.error.log;
}
